ktor {
    deployment {
        host = "0.0.0.0"
        port = 8081
        port = ${?PORT}
        port = ${?WEB_PORT}
    }
    application {
        modules = [ lt.skautai.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/skautu_inventorius"
    url = ${?DB_URL}
    driver = "org.postgresql.Driver"
    user = "postgres"
    user = ${?DB_USER}
    password = ""
    password = ${?DB_PASSWORD}
}

jwt {
    secret = ${JWT_SECRET}
    issuer = "lt.skautai.web"
    audience = "lt.skautai.web"
    realm = "skautu-inventorius-web"
}

setup {
    bootstrapToken = ""
    bootstrapToken = ${?SETUP_BOOTSTRAP_TOKEN}
}
